server:
  port: 9092

spring:
  datasource:
    url: jdbc:h2:mem:lostandfound
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /lostandfound

user:
  service:
    url: http://localhost:8081
